url: https://tolfaa.ml
baseurl: /

# Site settings
title: The Touch of Life
email: urvin@greenwooshigh.edu.in
description: "During the pandemic, access to medical care is scarce and the importance of first-aid has increased tremendously. In view of this, we conducted an online first-aid course, covering over common scenarios"


# Team names, titles and social links
people:
- name: Urvi Nath
  pic: 1
  position: Head 1
  social:
    - title: instagram
      url: https://www.instagram.com/__urviii_/
    - title: facebook
      url: example.com
    - title: linkedin
      url: example.com

- name: Rachitha Raghuram
  pic: 2
  position: Lead Marketer
  social:
    - title: instagram
      url: https://www.instagram.com/rachitha_1502/
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Muthu Adithya Ramnarayanan
  pic: 3
  position: Lead Developer
  social:
    - title: instagram
      url: https://instagram.com/muthuadithya
    - title: github
      url: https://github.com/muthu-beep
    - title: linkedin
      url: https://www.linkedin.com/in/muthu-adithya-ramnarayanan-374377198/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: example.com
  - title: facebook
    url: facebook.com
  - title: stack-overflow
    url: http://stackoverflow.com/
  - title: bitbucket 
    url: http://bitbucket.org/
  - title: github
    url: https://github.com/muthu-beep/The-Touch-of-life

# Postal address (add as many lines as necessary)
address:
  - line: Greenwood High Intl. School
  - line: Sarjapur Main Rd
  - line: Varthur, Karnataka

# Build settings
markdown: kramdown
permalink: pretty
