url: https://tolfaa.ml
baseurl: /

# Site settings
title: The Touch of Life
email: urvin@greenwooshigh.edu.in
description: "During the pandemic, access to medical care is scarce and the importance of first-aid has increased tremendously. In view of this, we conducted an online first-aid course, covering over common scenarios"


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: instagram
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Muthu Adithya Ramnarayanan
  pic: 3
  position: Lead Developer
  social:
    - title: instagram
      url: https://instagram.com/muthuadithya
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Greenwood High Intl. School
  - line: Sarjapur Main Rd
  - line: Varthur, Karnataka

# Build settings
markdown: kramdown
permalink: pretty
